server:
  port: 25008
  tomcat:
    uri-encoding: UTF-8
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cc?characterEncoding=utf-8&useSSL=false
  username: root
  password: password
spring:
  http:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
    encoding:
      charset: UTF-8
      force: false
      enabled: true
  rabbitmq:
    host: 10.196.20.103
    port: 5672
    username: test1
    password: test1
    virtual-host: /host
    template:
      exchange: v5orgsexchage
    publisher-confirms: true
logging:
  config: classpath:log4j2.xml
rest:
  ConnectTimeout: 60000
  ReadTimeout: 60000